-- 汉化中
UPDATE `locales_gossip_menu_option` SET `menu_id`='6162', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='6162') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='6023', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='6023') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4360', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4360') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4342', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4342') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4326', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4326') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4323', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4323') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4307', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4307') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4302', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4302') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4282', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4282') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4281', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4281') AND (`id`='0');
UPDATE `locales_gossip_menu_option` SET `menu_id`='4106', `id`='0', `option_text_loc1`=NULL, `option_text_loc2`='J\'ai besoin d\'une monture.', `option_text_loc3`='Ich brauche einen Flug.', `option_text_loc4`='我需要一个运输工具.', `option_text_loc5`=NULL, `option_text_loc6`=NULL, `option_text_loc7`=NULL, `option_text_loc8`='Мне нужен транспорт.', `box_text_loc1`=NULL, `box_text_loc2`=NULL, `box_text_loc3`=NULL, `box_text_loc4`=NULL, `box_text_loc5`=NULL, `box_text_loc6`=NULL, `box_text_loc7`=NULL, `box_text_loc8`=NULL WHERE (`menu_id`='4106') AND (`id`='0');
